export const GRADE_ADJUSTMENTS_MODAL = 'GRADE_ADJUSTMENTS_MODAL';
export const MANAGE_FEES_MODAL = 'MANAGE_FEES_MODAL';
export const SELECT_SCHOOL_MODAL = 'SELECT_SCHOOL_MODAL';
export const MISGRID_APPROVAL_MODAL = 'MISGRID_APPROVAL_MODAL';
